name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank's for taking the time to contribute! We will get back to you as fast as we can."
        pr-message: "Thank's for taking the time to contribute! We will go over your pull request and make any necessary changes as fast as we can."
